"""merchant_retry_policy

Revision ID: 17edd9d7cb01
Revises: 3b7fb2b72b99
Create Date: 2026-08-29 11:48:54.598157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17edd9d7cb01'
down_revision: Union[str, Sequence[str], None] = '3b7fb2b72b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_retry_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('fallback_days', sa.Integer(), nullable=True),
    sa.Column('fallback_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_name')
    )
    op.create_index(op.f('ix_merchant_retry_policy_id'), 'merchant_retry_policy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_retry_policy_id'), table_name='merchant_retry_policy')
    op.drop_table('merchant_retry_policy')
    # ### end Alembic commands ###
