"""bank_status_hysteresis

Revision ID: 3b7fb2b72b99
Revises: e43c38d30ea3
Create Date: 2026-08-29 11:43:55.926754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7fb2b72b99'
down_revision: Union[str, Sequence[str], None] = 'e43c38d30ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_status', sa.Column('normal_windows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_status', 'normal_windows_count')
    # ### end Alembic commands ###
