"""razorpay_mandate_fields

Revision ID: e43c38d30ea3
Revises: 0356ffbefe37
Create Date: 2026-08-29 11:30:57.299155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43c38d30ea3'
down_revision: Union[str, Sequence[str], None] = '0356ffbefe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mandates', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.add_column('mandates', sa.Column('razorpay_token_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mandates', 'razorpay_token_id')
    op.drop_column('mandates', 'razorpay_customer_id')
    # ### end Alembic commands ###
